### PR TITLE
Updates the brick only QP simulation to a proper set of unit tests.

### PR DESCRIPTION
**Pull request by rcory**
Also fixes a bug in the contact force QP's integral controller,
where the integral error state was being reset incorrectly.

---
This change is [Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/18)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review please.

> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/18#-:-MDW8j2eEI2UVPlp2RQ5:b-jjzuh1)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/18#-:-MDXL5_xDc1ph6MyW41T:bg7igkv)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 40 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXJy6R44SO_GWQi3q9:-MDXJy6R44SO_GWQi3qA:b-w0zcav) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L40)):*
> ```cpp
>  protected:
>   void BuildDiagram(
>       BrickType brick_type, VectorXd brick_q0, VectorXd brick_qf,
> ```

Eigen:VectorXd -> const Eigen::VectorXd&
___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 41 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXK31X4rCulgKIbohY:-MDXK31X4rCulgKIbohZ:byghuar) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L41)):*
> ```cpp
>   void BuildDiagram(
>       BrickType brick_type, VectorXd brick_q0, VectorXd brick_qf,
>       std::unordered_map<Finger, BrickFaceInfo> finger_face_assignments,
> ```

Ditto, use const reference?
___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 71 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXKCDQ6HoEyhciggsa:-MDXKCDQ6HoEyhciggsb:b-dc6awe) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L71)):*
> ```cpp
>       throw std::logic_error("Unknown brick type.");
>     }
>     planar_gripper_->set_penetration_allowance(0.2);
> ```

That is a pretty big penetration allowance, the brick size is 0.1, this is larger than the brick size?

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/18)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 40 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXJy6R44SO_GWQi3q9:-MDpBYuV2Ub1k-hgyOD5:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L40)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Eigen:VectorXd -> const Eigen::VectorXd&
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 41 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXK31X4rCulgKIbohY:-MDpBZEs6HBbzk-HdaBe:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L41)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto, use const reference?
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/brick_only_qp_test.cc, line 71 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/18#-MDXKCDQ6HoEyhciggsa:-MDpI3-h8Eqsx7WAL5lI:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/5f89d746c264260d0c68c8b5144fea12a08bbcbd/examples/planar_gripper/test/brick_only_qp_test.cc#L71)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

That is a pretty big penetration allowance, the brick size is 0.1, this is larger than the brick size?
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
