### PR TITLE
Add models with texture and a camera

### PR DESCRIPTION
**Pull request by huihuaTRI**
This PR does two things
1) Add two brick models (one pinned and one planar) with textures.
2) Add a camera on top of the platform. Both the depth and color images will be published via lcm at 10Hz. If speed is a concern, we could reduce the frequency and get rid of the depth image.

Here is an image of the result:
planar_gripper_camera_planar_brick

---
This change is [Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16)

### CODE REVIEW

**Review by rcory — CHANGES_REQUESTED** [review]
Is there a good reason we don't just add the texture information to the existing brick `.sdf` files? I presume we can tell drake visualizer what type of geometry to display (i.e., perception vs. illustration)?

If we duplicate these files then we open up the possibility of having these files get out of sync. More importantly though, it's also not entirely clear to me that we need the duplication at all.

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16#-:-MDLfokm6JM8NLHgbntC:b4eq0iz)* status: all files reviewed, 16 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/BUILD.bazel, line 291 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLdZv2Atq8Crfq5rRn:-MDLdZv2Atq8Crfq5rRo:b-j4qm8i) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/BUILD.bazel#L291)):*
> ```Starlark
>     add_test_rule = 1,
>     data = [
>         ":models",
> ```

Why add this dependency?
___
*[examples/planar_gripper/planar_gripper.h, line 44 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLdwZx3W6n0D1E3YxY:-MDLdwZx3W6n0D1E3YxZ:b-ljv9a1) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L44)):*
> ```objc
> 
>   /// Sets up the diagram using the planar brick with texture.
>   void SetupPlanarBrickWithTexture(std::string orientation);
> ```

Why not just add the textured brick to the existing `SetupPlanarBrick` method? I can't think of a good reason to have a separate setup method just for the textured brick.
___
*[examples/planar_gripper/planar_gripper.h, line 289 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLjZjG6nVwalYvP1dX:-MDLjZjG6nVwalYvP1dY:b-e19lw2) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L289)):*
> ```objc
>     return plant_->num_multibody_states(brick_index_);
>   }
>   std::string get_default_camera_name() const { return default_camera_name_; }
> ```

nit add space above this line
___
*[examples/planar_gripper/planar_gripper.h, line 328 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLjhLpE9eFIt128O_B:-MDLjhLpE9eFIt128O_C:b-gi8aaw) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L328)):*
> ```objc
>                                systems::DiagramBuilder<double>* builder);
> 
>   /// Adds a RGBD camera to the diagram.
> ```

a -> an
___
*[examples/planar_gripper/planar_gripper.cc, line 528 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLkS0k50-CBk415hr3:-MDLkS0k50-CBk415hr4:b3b0gn8) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L528)):*
> ```cpp
>              "drake/examples/planar_gripper/models/bricks_with_texture/"
>              "planar_brick_with_texture.sdf");
> }
> ```

Don't think we need this (See top level comment regarding textured model)
___
*[examples/planar_gripper/planar_gripper.cc, line 601 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLkhmx0ZXGxr1di8Ub:-MDLkhmx0ZXGxr1di8Uc:b-tu26do) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L601)):*
> ```cpp
> }
> 
> systems::sensors::RgbdSensor* PlanarGripper::AddCamera(
> ```

BTW is there any performance advantage to making adding a camera optional? Not sure if we need to, but was curious based on your experience with FLT.
___
*[examples/planar_gripper/planar_gripper.cc, line 605 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLlPUZ8RB-7Bf4Cdp-:-MDLlPU_7K1UWfjvdAKH:bs0c154) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L605)):*
> ```cpp
>     const std::string& camera_name, systems::DiagramBuilder<double>* builder) {
>   DRAKE_DEMAND(builder != nullptr);
>   // Add a default render.
> ```

renderer
___
*[examples/planar_gripper/planar_gripper.cc, line 773 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLmqJ54vb7-ffBDXpA:-MDLmqJ54vb7-ffBDXpB:b-m78ti2) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L773)):*
> ```cpp
>   }
> 
>   // Add a rgbd camera sits on top of the planar gripper platform. The camera
> ```

"Adds _an_ rgbd camera _that_ sits ..."
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 82 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLqAm2DAsw_bXnlJmK:-MDLqAm2DAsw_bXnlJmL:b-q615qz) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L82)):*
> ```cpp
> #include "drake/systems/lcm/lcm_publisher_system.h"
> #include "drake/systems/lcm/lcm_subscriber_system.h"
> #include "drake/systems/sensors/image_to_lcm_image_array_t.h"
> ```

Can you please add instructions (perhaps to the top level README) on what one needs to do in order to see the camera view windows?
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 120 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLgts3DtKxyXoT7X8q:-MDLgts44jE_d0ghkoe7:b-1972mo) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L120)):*
> ```cpp
>             "Visualize contacts in Drake visualizer.");
> DEFINE_string(brick_type, "planar",
>               "The brick type {pinned, planar, textured_planar}");
> ```

Don't think we need a third option. See top level comment regarding textured model.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 151 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLh0YrD-hsFaLm-7pZ:-MDLh0YrD-hsFaLm-7p_:b-1972mo) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L151)):*
> ```cpp
>     planar_gripper->SetupPlanarBrick(FLAGS_orientation);
>   } else if (FLAGS_brick_type == "textured_planar") {
>     planar_gripper->SetupPlanarBrickWithTexture(FLAGS_orientation);
> ```

Don't think we need a third option. See top level comment regarding textured model.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 210 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLhQtoEJIwJr6ixp2l:-MDLhQtoEJIwJr6ixp2m:b-sg3afb) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L210)):*
> ```cpp
>   geometry::ConnectDrakeVisualizer(
>       &builder, planar_gripper->get_mutable_scene_graph(),
>       planar_gripper->GetOutputPort("pose_bundle"));
> ```

I see you removed the `lcm` object being passed in here. Why? If not passed in, Drake will create another instance internally (which is wasteful).

Also, could we have a gflag control what type of visualization we want drake visualizer to have, i.e., `geometry::Role::kIllustration` or `geometry::Role::kPerception`?
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 236 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLoSDJ67gHRjDS0Jpl:-MDLoSDJ67gHRjDS0Jpm:b-qmqfyl) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L236)):*
> ```cpp
>                                                      camera_name);
>   builder.Connect(planar_gripper->GetOutputPort(camera_name + "_depth_image"),
>                   depth_cam_port);
> ```

Could we move the above camera image setup code to the `PlanarGripper` class, and just export `image_array_t_msg_output_port`? Seems it would make the code more compact and reusable.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 338 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpCZEEtHig4e4uskX:-MDLpCZEEtHig4e4uskY:b-qpnx85) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L338)):*
> ```cpp
>   init_brick_pos_map["brick_revolute_x_joint"] =
>       brick_keyframe_info.first(rx_index, 0);
>   if (FLAGS_brick_type == "planar" || FLAGS_brick_type == "textured_planar") {
> ```

Don't think we need another option. See top level comment regarding textured model.
___
*[examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, line 58 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpLP3DspZM249HlLv:-MDLpLP3DspZM249HlLw:b7i3o6o) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc#L58)):*
> ```cpp
>       "drake/examples/planar_gripper/models/planar_gripper.sdf");
>   MultibodyPlant<double> plant(1e-3 /* to suppress continuous time warnings */);
> ```

extra line space?
___
*[examples/planar_gripper/models/bricks_with_texture/brick_with_texture_1dof.sdf, line 4 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpRp202zjEbnpiAz1:-MDLpRp202zjEbnpiAz2:b-6m81ss) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/models/bricks_with_texture/brick_with_texture_1dof.sdf#L4)):*
> ```
> 
> <sdf version="1.6">
>   <model name="brick_with_texture_1dof">
> ```

Don't think we need another file. See top level comment regarding textured model.
___
*[examples/planar_gripper/models/bricks_with_texture/planar_brick_with_texture.sdf, line 3 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpZsTBdHLt4wwRz9T:-MDLpZsTBdHLt4wwRz9U:b-6m81ss) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/models/bricks_with_texture/planar_brick_with_texture.sdf#L3)):*
> ```
> <?xml version="1.0"?>
> <sdf version='1.6'>
> <model name="planar_brick_with_texture">
> ```

Don't think we need another file. See top level comment regarding textured model.

**Review by rcory — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16)* status: all files reviewed, 17 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/planar_gripper.h, line 336 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDMZbI23BjqBhCoPZFW:-MDMZbI23BjqBhCoPZFX:b-q2rut8) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L336)):*
> ```objc
>   /// will throw if this pointer is a nullptr. Currently, it only supports
>   /// adding one camera and the camera properties are hard-coded.
>   systems::sensors::RgbdSensor* AddCamera(
> ```

Can you add a unit test for this?

**Review by huihuaTRI — COMMENTED** [review]
Comments are fixed. PTAL. Thanks

> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16#-:-MDNKFwb3zGsPTBUD8c1:b5le271)* status: 2 of 15 files reviewed, 16 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/BUILD.bazel, line 291 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLdZv2Atq8Crfq5rRn:-MDNIifJ0Igl6EZ_bivJ:bxmbe44) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/BUILD.bazel#L291)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Why add this dependency?
</blockquote></details>

Done. When I was working on this, you have not moved the models into the models folder. So, it's some residual that I forgot to remove.
___
*[examples/planar_gripper/planar_gripper.h, line 44 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLdwZx3W6n0D1E3YxY:-MDNJPoP1f5Jyq0mUDwu:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L44)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Why not just add the textured brick to the existing `SetupPlanarBrick` method? I can't think of a good reason to have a separate setup method just for the textured brick.
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.h, line 328 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLjhLpE9eFIt128O_B:-MDNJRJv8vps_wEkZBnT:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L328)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

a -> an
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.h, line 336 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDMZbI23BjqBhCoPZFW:-MDNJSVs1eIVhigLxuBh:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.h#L336)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Can you add a unit test for this?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 528 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLkS0k50-CBk415hr3:-MDNJVox-SOChgQ6y8mB:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L528)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need this (See top level comment regarding textured model)
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 601 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLkhmx0ZXGxr1di8Ub:-MDNJXTGEQe7j5PNLrDj:brsol0q) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L601)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

BTW is there any performance advantage to making adding a camera optional? Not sure if we need to, but was curious based on your experience with FLT.
</blockquote></details>

Adding a camera will for sure slow-down the simulation. "How much" depends on the image size and publish rate. I checked the current setup, it runs with 1.0 real-time factor fine.
___
*[examples/planar_gripper/planar_gripper.cc, line 605 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLlPUZ8RB-7Bf4Cdp-:-MDNJqSm7wB2wW75Gc7j:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L605)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

renderer
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper.cc, line 773 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLmqJ54vb7-ffBDXpA:-MDNJsaU9b8GhHu9Jgcm:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/planar_gripper.cc#L773)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

"Adds _an_ rgbd camera _that_ sits ..."
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 82 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLqAm2DAsw_bXnlJmK:-MDNJuxM6z6yZW5xywE_:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L82)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Can you please add instructions (perhaps to the top level README) on what one needs to do in order to see the camera view windows?
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 120 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLgts3DtKxyXoT7X8q:-MDNJwJZ4Hd4Mv7ZHn8x:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L120)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need a third option. See top level comment regarding textured model.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 151 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLh0YrD-hsFaLm-7pZ:-MDNJwwB2mTDeMOG8zeC:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L151)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need a third option. See top level comment regarding textured model.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 210 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLhQtoEJIwJr6ixp2l:-MDNK0xS9AA0D--tmOao:b-6zm68i) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L210)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

I see you removed the `lcm` object being passed in here. Why? If not passed in, Drake will create another instance internally (which is wasteful).

Also, could we have a gflag control what type of visualization we want drake visualizer to have, i.e., `geometry::Role::kIllustration` or `geometry::Role::kPerception`?
</blockquote></details>

As discussed offline, this one is a mistake. Fixed now.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 236 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLoSDJ67gHRjDS0Jpl:-MDNK6Kl1Kkjhd9VzUK8:b1c5ibk) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L236)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Could we move the above camera image setup code to the `PlanarGripper` class, and just export `image_array_t_msg_output_port`? Seems it would make the code more compact and reusable.
</blockquote></details>

Done. Good suggestion.
___
*[examples/planar_gripper/run_planar_gripper_simulation.cc, line 338 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpCZEEtHig4e4uskX:-MDNK8E89uR5zKMhn6Hi:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_simulation.cc#L338)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need another option. See top level comment regarding textured model.
</blockquote></details>

Done.
___
*[examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, line 58 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpLP3DspZM249HlLv:-MDNKAb_0Nv388zuVUaO:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc#L58)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

extra line space?
</blockquote></details>

Done.
___
*[examples/planar_gripper/models/bricks_with_texture/brick_with_texture_1dof.sdf, line 4 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpRp202zjEbnpiAz1:-MDNKC782Mk4APYwJ1xl:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/models/bricks_with_texture/brick_with_texture_1dof.sdf#L4)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need another file. See top level comment regarding textured model.
</blockquote></details>

Done.
___
*[examples/planar_gripper/models/bricks_with_texture/planar_brick_with_texture.sdf, line 3 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDLpZsTBdHLt4wwRz9T:-MDNKCWA8W9la8QlgmUi:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e26a682bfd1e162e156fb69ddbb001fa7915952/examples/planar_gripper/models/bricks_with_texture/planar_brick_with_texture.sdf#L3)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Don't think we need another file. See top level comment regarding textured model.
</blockquote></details>

Done.

**Review by rcory — APPROVED** [review]
:lgtm: (w/ a couple nits)

> Reviewed 14 of 16 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16#-:-MDQWkSf3aW-Fh2kjcEV:b-k1ughv)* status: all files reviewed, 4 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/planar_gripper.h, line 332 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQU1ZsAdvr97JxcSfn:-MDQU1ZsAdvr97JxcSfo:bz3elz) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/planar_gripper.h#L332)):*
> ```objc
>   /// will throw if this pointer is a nullptr. Currently, it only supports
>   /// adding one camera and the camera properties are hard-coded.
>   /// A "{camera_name}_images" output port will be created after calling this
> ```

nit add a `@note` to separate this paragraph from the previous `@param`
___
*[examples/planar_gripper/models/1dof_brick.sdf, line 42 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWPoq3ORSuwEOctnn:-MDQWPoq3ORSuwEOctno:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/1dof_brick.sdf#L42)):*
> ```
>     </visual>
>     <visual name='brick_perception_texture'>
>       
> ```

nit can you line wrap this long line?
___
*[examples/planar_gripper/models/planar_brick.sdf, line 92 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWSTO83ACjnSdjC1C:-MDQWSTO83ACjnSdjC1D:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/planar_brick.sdf#L92)):*
> ```
>     </visual>
>     <visual name='brick_perception_texture'>
>       
> ```

nit can you line wrap this long line?
___
*[examples/planar_gripper/models/meshes/README.md, line 7 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWblB1FFgPrf77Yss:-MDQWblB1FFgPrf77Yst:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/meshes/README.md#L7)):*
> ```Markdown
> Drake will automatically load the `.mtl` file (if there is a proper one) and use it for illustration.
> 
> In the future, if we want to use the texture for illustration, we only need to rename the `.mtl` file to be the same name as the `.obj`.
> ```

nit can you line wrap this long line?

**Review by rcory — APPROVED** [review]
:lgtm: (w/ a couple nits)

> Reviewed 14 of 16 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16#-:-MDQWkSf3aW-Fh2kjcEV:b-k1ughv)* status: all files reviewed, 4 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/planar_gripper.h, line 332 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQU1ZsAdvr97JxcSfn:-MDQU1ZsAdvr97JxcSfo:bz3elz) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/planar_gripper.h#L332)):*
> ```objc
>   /// will throw if this pointer is a nullptr. Currently, it only supports
>   /// adding one camera and the camera properties are hard-coded.
>   /// A "{camera_name}_images" output port will be created after calling this
> ```

nit add a `@note` to separate this paragraph from the previous `@param`
___
*[examples/planar_gripper/models/1dof_brick.sdf, line 42 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWPoq3ORSuwEOctnn:-MDQWPoq3ORSuwEOctno:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/1dof_brick.sdf#L42)):*
> ```
>     </visual>
>     <visual name='brick_perception_texture'>
>       
> ```

nit can you line wrap this long line?
___
*[examples/planar_gripper/models/planar_brick.sdf, line 92 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWSTO83ACjnSdjC1C:-MDQWSTO83ACjnSdjC1D:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/planar_brick.sdf#L92)):*
> ```
>     </visual>
>     <visual name='brick_perception_texture'>
>       
> ```

nit can you line wrap this long line?
___
*[examples/planar_gripper/models/meshes/README.md, line 7 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/16#-MDQWblB1FFgPrf77Yss:-MDQWblB1FFgPrf77Yst:b-ywmtmm) ([raw file](https://github.com/visuomotordexterity/drake/blob/bfa6f2b3d758a11620fbc45848c599e712ffb99f/examples/planar_gripper/models/meshes/README.md#L7)):*
> ```Markdown
> Drake will automatically load the `.mtl` file (if there is a proper one) and use it for illustration.
> 
> In the future, if we want to use the texture for illustration, we only need to rename the `.mtl` file to be the same name as the `.obj`.
> ```

nit can you line wrap this long line?

**Review by rcory — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
