### PR TITLE
Updates force_control_test

### PR DESCRIPTION
**Pull request by rcory**
Also adds some cleanup/fixes

---
This change is [Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@huihuatri for review please.

> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17#-:-MDLVw_OBqbmnCtH8Ri8:bvie2wq)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @huihuaTRI)

**Review by huihuaTRI — COMMENTED** [review]
First pass is done with some minor comments. I will switch a computer and want to publish this just in case it gets lost.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17#-:-MDRWgEM3GBlOi_aXwNq:b-emoe4m)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @huihuaTRI and @rcory)

___
*[examples/planar_gripper/README.md, line 29 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDROInbBUvRumtMi2b9:-MDROInbBUvRumtMi2bA:b-qhqamo) ([raw file](https://github.com/visuomotordexterity/drake/blob/2930b542c34f796873188013471f506d0bf3a564/examples/planar_gripper/README.md#L29)):*
> ```Markdown
> Before running the example, launch the visualizer:
> ```
> ./bazel-bin/tools/drake_visualizer
> ```

nit: the `./` is not necessary. Probably good to keep it consistent with the rest by removing it?
___
*[examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, line 94 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDRPz1I0Yw_VRFaJnfP:-MDRPz1I0Yw_VRFaJnfQ:b-dqwcv0) ([raw file](https://github.com/visuomotordexterity/drake/blob/2930b542c34f796873188013471f506d0bf3a564/examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc#L94)):*
> ```cpp
>   auto gripper_command_pub = builder.AddSystem(
>       systems::lcm::LcmPublisherSystem::Make<lcmt_planar_gripper_command>(
>           kLcmGripperCommandChannel, &lcm, kGripperLcmPeriod));
> ```

nit: it took me a while to figure out where does `kGripperLcmPeriod` come from. I also think in general, it's not a good idea to use a constant this way. It can easily get shadowed if someone defines a constant that has the same name. 

For a parameter that gets shared in different cases, I found this (using a singleton) being a very good way https://github.awsinternal.tri.global/robotics/enabling-anzu/blob/master/sim/dish/parameters.h. I used it for the FL simulation also.

This could also improve the code by removing a lot of bolier plate GFLAGS definition.
___
*[examples/planar_gripper/test/force_control_stabilization.cc, line 372 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDRV3oT2gvxoO04ZdN8:-MDRV3oU4e9V5m2zbdLD:b-wfngzl) ([raw file](https://github.com/visuomotordexterity/drake/blob/2930b542c34f796873188013471f506d0bf3a564/examples/planar_gripper/test/force_control_stabilization.cc#L372)):*
> ```cpp
>       &finger_joint_name_to_row_index_map);
> 
>   // Re-scale the time vector (to allow speed-up or slow-down of keyframe
> ```

nit: **Re-scale** means it is already a scaled time.  Is this true? I am trying to understand here.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @huihuaTRI)

___
*[examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, line 94 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDRPz1I0Yw_VRFaJnfP:-MDWWOwzAK8GbY3NI2sv:bogzczk) ([raw file](https://github.com/visuomotordexterity/drake/blob/2930b542c34f796873188013471f506d0bf3a564/examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc#L94)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

nit: it took me a while to figure out where does `kGripperLcmPeriod` come from. I also think in general, it's not a good idea to use a constant this way. It can easily get shadowed if someone defines a constant that has the same name. 

For a parameter that gets shared in different cases, I found this (using a singleton) being a very good way https://github.awsinternal.tri.global/robotics/enabling-anzu/blob/master/sim/dish/parameters.h. I used it for the FL simulation also.

This could also improve the code by removing a lot of bolier plate GFLAGS definition.
</blockquote></details>

I like this idea! I plan to consolidate gflags/parameters in a different PR. For now, I've added a simple get method that at least makes it less likely to be shadowed.

**Review by huihuaTRI — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: all files reviewed, 7 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, line 94 at r1](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDRPz1I0Yw_VRFaJnfP:-MDWp51ECpvmjOeeGHHG:b-vaabct) ([raw file](https://github.com/visuomotordexterity/drake/blob/2930b542c34f796873188013471f506d0bf3a564/examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc#L94)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

I like this idea! I plan to consolidate gflags/parameters in a different PR. For now, I've added a simple get method that at least makes it less likely to be shadowed. 
</blockquote></details>

sgtm. When I say "a while", I was exaggerating. Probably only 1minute. :)
___
*[examples/planar_gripper/test/force_control_test.cc, line 32 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX1Tv7-9_ClASv79iC:-MDX1Tv7-9_ClASv79iD:b-b9ty6d) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L32)):*
> ```cpp
> using multibody::SpatialForce;
> 
> class SpatialForceVizSrc final : public systems::LeafSystem<double> {
> ```

nit: since this class is for testing, it should be put in the anonymous namespace.
___
*[examples/planar_gripper/test/force_control_test.cc, line 71 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX0uGuAb5b8DR8J72o:-MDX0uGuAb5b8DR8J72p:bvtnzkx) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L71)):*
> ```cpp
>               .contact_point();
>       SpatialForce<double> SF_Bq_W(Vector3d::Zero(), F_Bq_W);
>       spatial_force_viz_output->emplace_back(
> ```

I don't quite follow here. It seems to me that you always consider only one pair of contact, therefore, only one spatial force. Why you need a vector as the output type?

Also, it would be nice to have one sentence of a high-level summary about what this class does. I got the idea from the comment above the `DeclareAbstractOutputPort`
___
*[examples/planar_gripper/test/force_control_test.cc, line 83 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX1d92AfItsnabYJQ_:-MDX1d92AfItsnabYJQa:b-b9ty6d) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L83)):*
> ```cpp
> /// planar finger and a fixed brick, and the test checks the ForceController's
> /// ability to regulate a fixed force against the surface of the brick.
> class ForceControlTest : public testing::Test {
> ```

nit: since this class is for testing, it should be put in the anonymous namespace.
___
*[examples/planar_gripper/test/force_control_test.cc, line 106 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX26dIEjeqS_zTRORj:-MDX26dIEjeqS_zTRORk:br2xm5r) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L106)):*
> ```cpp
>     // Adds a single fixed brick (specifically for force control testing).
>     std::string brick_filename;
>     switch (brick_type) {
> ```

 It seems like the class comment is outdated since you now consider different brick types.
___
*[examples/planar_gripper/test/force_control_test.cc, line 183 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX5C6NCbIwvWQkGdms:-MDX5C6O0nYrZPUvPgGX:bdtaxq5) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L183)):*
> ```cpp
> 
>     // Connect the "virtual" force sensor to the force controller.
>     auto zoh_contact_results =
> ```

I don't quite get why the ZeroOrderHold system is needed here. The step size of the plant is 1e-3, which is the same as the period of the ZeroOrderHold system.  
___
*[examples/planar_gripper/test/force_control_test.cc, line 318 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDXBaYF79Ujwf1biNop:-MDXBaYF79Ujwf1biNoq:bb343xk) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L318)):*
> ```cpp
> };
> 
> // Test a single finger pushing against a fixed brick on its positive-z face.
> ```

nit: I would suggest adding some high-level comments about the numbers you are using. Then point out that the other tests are similar.
___
*[examples/planar_gripper/test/force_control_test.cc, line 367 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDXB0XtB4VjS1h-SwCa:-MDXB0XtB4VjS1h-SwCb:b-tgrfa2) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L367)):*
> ```cpp
> }
> 
> // Test a single finger pushing against a fixed brick on its positive-y face.
> ```

nit: maybe add some comment to point out what is the difference between this test and the previous one.
___
*[examples/planar_gripper/test/force_control_test.cc, line 381 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDXD4VeER4pbNh_Mnh_:-MDXD4VeER4pbNh_Mnha:b-bx4f7z) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L381)):*
> ```cpp
>   EXPECT_TRUE(CompareMatrices(
>       Eigen::Vector2d::Ones(),
>       (final_actual_force.array() / desired_force.array()).matrix(), 2e-2));
> ```

btw: do you foresee this number is same across different test cases. If yes, probably worth defining a `constexpr double kPercetageThreshold = 2e-2`.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 71 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX0uGuAb5b8DR8J72o:-MDosAEeCcZGDBjj6OA-:byrmrf0) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L71)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

I don't quite follow here. It seems to me that you always consider only one pair of contact, therefore, only one spatial force. Why you need a vector as the output type?

Also, it would be nice to have one sentence of a high-level summary about what this class does. I got the idea from the comment above the `DeclareAbstractOutputPort`
</blockquote></details>

The generic system `SpatialForcesToLcm` [(link)](https://github.com/VisuoMotorDexterity/drake/blob/c683367032a92ee99da7113d845fa8a4ecfe1aa9/multibody/plant/spatial_forces_to_lcm.h#L21) which sends visualization messages to drake visualizer declares an input port of vector type, hence the output of this system is of vector type.
___
*[examples/planar_gripper/test/force_control_test.cc, line 106 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX26dIEjeqS_zTRORj:-MDotnJR4ToX0H8k4iRp:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L106)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

 It seems like the class comment is outdated since you now consider different brick types.
</blockquote></details>

Done.
___
*[examples/planar_gripper/test/force_control_test.cc, line 183 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX5C6NCbIwvWQkGdms:-MDou8r_8TzR4RN8Xwob:b-3dds2k) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L183)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

I don't quite get why the ZeroOrderHold system is needed here. The step size of the plant is 1e-3, which is the same as the period of the ZeroOrderHold system.  
</blockquote></details>

The zero order hold is to break the algebraic loop in the contact force output of the force controller. The force controller depends on the MBP contact results, and the MBP contact results depends on the forces commanded by the force controller...hence the loop.

**Review by huihuaTRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @huihuaTRI and @rcory)

___
*[examples/planar_gripper/test/force_control_test.cc, line 71 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX0uGuAb5b8DR8J72o:-MDpJ2Iz1lt-koNk13WQ:b-iycmfn) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L71)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

The generic system `SpatialForcesToLcm` [(link)](https://github.com/VisuoMotorDexterity/drake/blob/c683367032a92ee99da7113d845fa8a4ecfe1aa9/multibody/plant/spatial_forces_to_lcm.h#L21) which sends visualization messages to drake visualizer declares an input port of vector type, hence the output of this system is of vector type.
</blockquote></details>

Got you. Thanks.
___
*[examples/planar_gripper/test/force_control_test.cc, line 106 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX26dIEjeqS_zTRORj:-MDpJBZ4-lWA61JZQ951:btdyh05) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L106)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I have been unclear. The class comment (at the beginning of this class) also needs an update.
___
*[examples/planar_gripper/test/force_control_test.cc, line 183 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX5C6NCbIwvWQkGdms:-MDpJJUE347OVe0I8WLZ:b-182l9n) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L183)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

The zero order hold is to break the algebraic loop in the contact force output of the force controller. The force controller depends on the MBP contact results, and the MBP contact results depends on the forces commanded by the force controller...hence the loop.
</blockquote></details>

I see. It would be nice to add your explanation as a comment for this code.
Besides that, I still have two questions
1. To break the loop, do you intentionally want the update rate of the `ZeroOrderHold` to be the same as the time step? If yes (which I think should be the case), then probably should define a constant. Then use that constant in both cases.
2. Just to confirm, the ZOH will result in the contact result being delayed one simulation tick

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 183 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX5C6NCbIwvWQkGdms:-MDpMODYDjo1pzBfz51i:b-3lwf4a) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L183)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

I see. It would be nice to add your explanation as a comment for this code.
Besides that, I still have two questions
1. To break the loop, do you intentionally want the update rate of the `ZeroOrderHold` to be the same as the time step? If yes (which I think should be the case), then probably should define a constant. Then use that constant in both cases.
2. Just to confirm, the ZOH will result in the contact result being delayed one simulation tick
</blockquote></details>

1. The zero order hold is not intentionally set to match the MBP discretization step. It is meant to match the force controller's calculation rate on the hardware (i.e., 1 KHz) - see update.
2. Yes, that's the point. Delay by one tick so that you break the algebraic loop.

Good comments!

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 106 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX26dIEjeqS_zTRORj:-MDpWnLk3JE38nM3rGQg:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L106)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

I have been unclear. The class comment (at the beginning of this class) also needs an update.
</blockquote></details>

Done.

**Review by huihuaTRI — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17#-:-MDpdgwU4q2X6euDuyDN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rcory)

___
*[examples/planar_gripper/test/force_control_test.cc, line 183 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDX5C6NCbIwvWQkGdms:-MDpdX_MDg5vNMfL4RW2:b-ucfknh) ([raw file](https://github.com/visuomotordexterity/drake/blob/e301950b06f6659a86fd1456b3fbf1c9c808f51c/examples/planar_gripper/test/force_control_test.cc#L183)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

1. The zero order hold is not intentionally set to match the MBP discretization step. It is meant to match the force controller's calculation rate on the hardware (i.e., 1 KHz) - see update.
2. Yes, that's the point. Delay by one tick so that you break the algebraic loop.

Good comments!
</blockquote></details>

Thanks!
___
*[examples/planar_gripper/test/force_control_test.cc, line 186 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdYuf1H1vbN49Mahi:-MDpdYuf1H1vbN49Mahj:b-1iwqkb) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L186)):*
> ```cpp
> 
>     // This time step matches that of the hardware force controller.
>     const double force_control_step = 1e-3;
> ```

nit: per GSG should be `kForceControlStep`
___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpdcQU6JUSGR1tbfJz:b-bezuku) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
> ```cpp
>     // This zero order hold breaks an algebraic loop in the force controller,
>     // where the output force depends on MBP's contact results, and MBP's
>     // contact results depends on the force controller's output.
> ```

nit: depend -> depends

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: all files reviewed, 1 unresolved discussion (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpgWGU67dglrP1nB8i:b-f4kefl) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

nit: depend -> depends
</blockquote></details>

? (not sure where you see singular "depend")

**Review by huihuaTRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @huihuaTRI and @rcory)

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpwx2F50ERC3L3nj--:b3xq7zh) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

? (not sure where you see singular "depend")
</blockquote></details>

ha, my bad, should be "contact results depends" -> depend.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpxL-YDV3S9Lg10A_6:b-w4ptm) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

ha, my bad, should be "contact results depends" -> depend. 
</blockquote></details>

hmmm, grammatically this is wrong. And stating that contact results specifically is the dependent variable isn't a bad thing. I guess I'm saying I disagree with you on this. Perhaps I'm missing something else (feel free to elaborate).

**Review by huihuaTRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @huihuaTRI and @rcory)

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpxwYv3lUSG8CDRbLU:b-fgbaos) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

hmmm, grammatically this is wrong. And stating that contact results specifically is the dependent variable isn't a bad thing. I guess I'm saying I disagree with you on this. Perhaps I'm missing something else (feel free to elaborate).
</blockquote></details>

"results" is a plural, therefore, we should use "depend" other than "depends". This is what I mean.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @huihuaTRI)

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDpydqc0rgTnc7jzvxw:b-p0yjtf) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, huihuaTRI wrote…</i></summary><blockquote>

"results" is a plural, therefore, we should use "depend" other than "depends". This is what I mean.
</blockquote></details>

I see the dilemma. I am referring to the object `ContactResults` (singular), not the individual components of the results (plural). I've updated the doc with the correct object name.

**Review by huihuaTRI — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/17)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[examples/planar_gripper/test/force_control_test.cc, line 190 at r5](https://reviewable.io/reviews/visuomotordexterity/drake/17#-MDpdcQT2L22nNEmP2EO:-MDq-mzY-R00naR2CrjB:b-85i648) ([raw file](https://github.com/visuomotordexterity/drake/blob/3a4e78adefd87843b5fbc50c045f745a3f8cb517/examples/planar_gripper/test/force_control_test.cc#L190)):*
<details><summary><i>Previously, rcory (Rick Cory) wrote…</i></summary><blockquote>

I see the dilemma. I am referring to the object `ContactResults` (singular), not the individual components of the results (plural). I've updated the doc with the correct object name.
</blockquote></details>

LGTM!

**Pull request merged**
