### PR TITLE
Adds a multi-contact plan feedback stabilization example.

### PR DESCRIPTION
**Pull request by rcory**
* Updates parser to accept keyframe files with contact mode
and time fields.

* Added the option to run a `regulation` or `tracking` task in
planar_gripper_rotate_simulation.

* Fixes a bug in force controller where I was incorrectly calculating
the contact point in brick frame (only rotating instead of xforming).
Also added zero derivative constraints to the spline brick trajectory.

* Adds an example demonstrating force-feedback stabilization of a
multi-contact plan for brick rotation.

* Adds integral control for stiction compensation (used in stabilization example).

---
This change is [Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12)

### CODE REVIEW

**Review by rcory — COMMENTED** [review]
+@hongkai-dai for review, please. 

The line count in this PR is a bit misleading, since a big portion of this PR introduces new keyframe files (which tends to bloat the PR line count). Although, I will admit that the actual new code line count is still sitting at a little bit over 1,000 lines. Sorry about that. If this becomes an issue, I can break it up for you.  Let me know.

> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12#-:-MCJjcz03xJdcFAz9WdI:b-wwn23n)* status: 0 of 43 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 8 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12)* status: 8 of 43 files reviewed, 5 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/contact_force_qp.h, line 172 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKuVFN5Zaj1IbQGIM-:-MCKuVFN5Zaj1IbQGIM0:b-967ijz) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.h#L172)):*
> ```objc
>       const Eigen::Ref<const Eigen::Matrix2d>& Kd_t,
>       const Eigen::Ref<const Eigen::Matrix2d>& Ki_t, double Kp_r, double Kd_r,
>       double Ki_r, double Ki_r_sat,  double Ki_t_sat, double weight_a_error,
> ```

I am a bit surprised to see that `Ki_t` is a matrix, while its integral saturation `Ki_t_sat` is a scalar. If `Ki_t(0, 0)` doesn't equal to `Ki_t(1, 1)`, should the saturation value be different for x direction versus y direction?
___
*[examples/planar_gripper/contact_force_qp.h, line 247 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKzSSs7TdPw6aKt7G9:-MCKzSSs7TdPw6aKt7GA:bd0yphz) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.h#L247)):*
> ```objc
> 
>  protected:
>   void DoCalcTimeDerivatives(
> ```

BTW, this function does not have a unit test. Just want to make sure it is intentional.
___
*[examples/planar_gripper/contact_force_qp.cc, line 198 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKvFwWCEaSbAoH9yGP:-MCKvFwWCEaSbAoH9yGQ:br4g2k8) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L198)):*
> ```cpp
>       mass_B_(mass_B),
>       I_B_(I_B) {
>   DRAKE_DEMAND(math::IsPositiveDefinite(Kp_t_));
> ```

I think the requirement on the PID control gain is not that they are positive definite? For example, for a simple PD control system `xddot = Kp * x + Kd * xdot`, the stability requires that all the eigen values of the matrix [0 I;Kp Kd] are on the left half plane? 

Do you suppose that `Kp_t, Kd_t, Ki_t` are all diagonal, hence the positiveness of the diagonal matrix is equivalent to each diagonal entry being positive?
___
*[examples/planar_gripper/contact_force_qp.cc, line 310 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKwX5445lDWiypBLTk:-MCKwX5506AEZzIIobQa:b-sthnqb) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L310)):*
> ```cpp
>   //  actually getting further away from the goal.
>   if (finger_face_assignments.size() == 1 && brick_type_ ==
>           BrickType::PlanarBrick) {
> ```

Hmm, could you throw a warning here? I think we need to fix the planning error. Maybe something like
```cpp
drake::log()->warn("Only one finger in contact with the planar brick, don't attempt to apply a force");
```
___
*[examples/planar_gripper/contact_force_qp.cc, line 423 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKyUFr5cOYNeOMqXoE:-MCKyUFr5cOYNeOMqXoF:bg3c2fm) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L423)):*
> ```cpp
> 
>     // y-translation.
>     if (state_block(0) > Ki_t_sat &&
> ```

nit, I think we could combine the three `if-else` blocks into a for loop, if we define `Eigen::Vector3d Ki_sat(Ki_t_sat, Ki_t_sat, Ki_r_sat)`, and then we could do
```c++
for (int i = 0; i < 3; ++i) {
  if ( (state_block(i) > Ki_sat(i) && desired_brick_positions(i) > brick_positions(i)) || (state_block(i) < -Ki_sat(i) && desired_brick_positions(i) < brick_positions(i))) {
  brick_positions = desired_brick_positions;
}
}
```
___
*[examples/planar_gripper/planar_gripper_common.h, line 130 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCL-I1OEcIR6z2J2PIJ:-MCL-I1OEcIR6z2J2PIK:b-gzdqit) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/planar_gripper_common.h#L130)):*
> ```objc
>  * planar_gripper_system.manipuland.vertices. For the brick case, edge 0 is the
>  * left (-y) edge, edge 1 is the top (+z) edge, edge 2 is the right (+y) edge,
>  * and edge 3 is the bottom (-z) edge. Do you think it is better to print the
> ```

This last sentence doesn't need to be in the documentation?

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Checkpoint.

> Reviewed 21 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12#-:-MCL140D085mHxo74xYi:by96gdd)* status: 29 of 43 files reviewed, 6 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/planar_gripper_utils.cc, line 174 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCL04TL4ht1F2ikQY9n:-MCL04TM0sF7QWecfW93:b-hw93t4) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/planar_gripper_utils.cc#L174)):*
> ```cpp
>       BrickFaceInfo face_info(*brick_faces.first.begin(),
>                               Eigen::Vector2d(brick_faces.second.tail<2>()),
>                               false /* no contact */);
> ```

When not-in-contact, p_BCb is set to the witness point, but p_WCb is not set, so now for the point Cb, its location in the world frame doesn't match with its location in the brick frame. I think we can actually move the computation of `p_WCb` out from the if branch above, such that this "else" branch can also access `p_WCb`?

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
First pass done.

> Reviewed 13 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12#-:-MCOglo-5pV5MV96jBYp:b-te4kzy)* status: 42 of 43 files reviewed, 7 unresolved discussions (waiting on @hongkai-dai and @rcory)

___
*[examples/planar_gripper/test/force_control_test.cc, line 138 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCOfnfF78KMP7l8w5C-:-MCOfnfF78KMP7l8w5C0:b-hdo5c9) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/test/force_control_test.cc#L138)):*
> ```cpp
>   // Draw the desired force in drake viz.
>   std::vector<multibody::SpatialForceOutput<double>> force_viz_vec;
>   Vector3d p_BoBq_W(0, -0.05202649, 0.017351387);
> ```

Curious where this number come from.

**Review by rcory — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12)* status: 28 of 43 files reviewed, 6 unresolved discussions (waiting on @hongkai-dai)

___
*[examples/planar_gripper/contact_force_qp.h, line 172 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKuVFN5Zaj1IbQGIM-:-MCOVazw7GgDb8tFC4bo:b-12evhp) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.h#L172)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am a bit surprised to see that `Ki_t` is a matrix, while its integral saturation `Ki_t_sat` is a scalar. If `Ki_t(0, 0)` doesn't equal to `Ki_t(1, 1)`, should the saturation value be different for x direction versus y direction?
</blockquote></details>

yes, good catch!
___
*[examples/planar_gripper/contact_force_qp.h, line 247 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKzSSs7TdPw6aKt7G9:-MCiFIKD3XB2pk-gVAcx:bafw6zs) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.h#L247)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, this function does not have a unit test. Just want to make sure it is intentional.
</blockquote></details>

The class `InstantaneousContactForceQPController` is missing unit tests in general. I will address this in a future PR.
___
*[examples/planar_gripper/contact_force_qp.cc, line 198 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKvFwWCEaSbAoH9yGP:-MCh3mgCCSjJcWaQOIOk:b-z88iwi) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L198)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think the requirement on the PID control gain is not that they are positive definite? For example, for a simple PD control system `xddot = Kp * x + Kd * xdot`, the stability requires that all the eigen values of the matrix [0 I;Kp Kd] are on the left half plane? 

Do you suppose that `Kp_t, Kd_t, Ki_t` are all diagonal, hence the positiveness of the diagonal matrix is equivalent to each diagonal entry being positive?
</blockquote></details>

This is a bug. These matrices should be strictly diagonal, since there should be no cross-coupling (off-diagonal) gains in this task. I've updated the API to enforce this. PTAL.
___
*[examples/planar_gripper/contact_force_qp.cc, line 310 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKwX5445lDWiypBLTk:-MChhxRA267fNTKrpHgS:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L310)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Hmm, could you throw a warning here? I think we need to fix the planning error. Maybe something like
```cpp
drake::log()->warn("Only one finger in contact with the planar brick, don't attempt to apply a force");
```
</blockquote></details>

Done.
___
*[examples/planar_gripper/contact_force_qp.cc, line 423 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCKyUFr5cOYNeOMqXoE:-MChvDwa8SlRkGlx9nlO:boyexb3) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/contact_force_qp.cc#L423)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

nit, I think we could combine the three `if-else` blocks into a for loop, if we define `Eigen::Vector3d Ki_sat(Ki_t_sat, Ki_t_sat, Ki_r_sat)`, and then we could do
```c++
for (int i = 0; i < 3; ++i) {
  if ( (state_block(i) > Ki_sat(i) && desired_brick_positions(i) > brick_positions(i)) || (state_block(i) < -Ki_sat(i) && desired_brick_positions(i) < brick_positions(i))) {
  brick_positions = desired_brick_positions;
}
}
```
</blockquote></details>

Done. Thanks!
___
*[examples/planar_gripper/planar_gripper_common.h, line 130 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCL-I1OEcIR6z2J2PIJ:-MChvNPGCBD9IUDti24o:b-896fix) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/planar_gripper_common.h#L130)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This last sentence doesn't need to be in the documentation?
</blockquote></details>

Done.
___
*[examples/planar_gripper/planar_gripper_utils.cc, line 174 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCL04TL4ht1F2ikQY9n:-MCi8mau25O_NHcJWGlF:b-58n6eb) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/planar_gripper_utils.cc#L174)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

When not-in-contact, p_BCb is set to the witness point, but p_WCb is not set, so now for the point Cb, its location in the world frame doesn't match with its location in the brick frame. I think we can actually move the computation of `p_WCb` out from the if branch above, such that this "else" branch can also access `p_WCb`?
</blockquote></details>

Good catch. I've removed `p_WCb` from the `BrickFaceInfo` structure, as it isn't necessary to keep redundant information in there. There was only one place in code that made use of it, so I moved the calculation of `p_WCb` there.
___
*[examples/planar_gripper/test/force_control_test.cc, line 138 at r2](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCOfnfF78KMP7l8w5C-:-MCiAq0n-rGadlkiBSa_:bow13g9) ([raw file](https://github.com/visuomotordexterity/drake/blob/4e82a1e9e22f067402adc3d1dfe8af02d71b06ee/examples/planar_gripper/test/force_control_test.cc#L138)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious where this number come from.
</blockquote></details>

Done. (added comment)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 43 files at r1, 14 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12#-:-MCiJFbaAskHCHDFLxCr:bg7igkv)* status: 42 of 43 files reviewed, all discussions resolved (waiting on @hongkai-dai)

___
*[examples/planar_gripper/planar_gripper_utils.h, line 21 at r3](https://reviewable.io/reviews/visuomotordexterity/drake/12#-MCiHsKGDH2rGL7-EDmi:-MCiHsKGDH2rGL7-EDmj:b-gfocse) ([raw file](https://github.com/visuomotordexterity/drake/blob/c35247707fdc00d45aec9ac84d74d2d8608b1c8d/examples/planar_gripper/planar_gripper_utils.h#L21)):*
> ```objc
> struct BrickFaceInfo {
>   BrickFaceInfo(const BrickFace face,
>                 const Eigen::Ref<const Vector2d> p_BCb,
> ```

BTW, we typically use `const Eigen::Ref<const Vector2d>&` (notice the & in the end) for passing-by-reference in Eigen.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/visuomotordexterity/drake/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
